train_file: [data/vqa_val_updated.json]
             
test_file: ['data/vqa_val_updated.json']
## val_file: ['data/vqa_val_updated.json']
answer_list: 'data/answer_list.json'

vqa_root: '/home/beast/Downloads/' #train2014/
vg_root: '/home/beast/Downloads/VG_100k/'  #image/

image_res: 224
batch_size_train: 16
batch_size_test: 16
k_test: 8
alpha: 0.4
distill: True
warm_up: True

eos: '[SEP]'

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 5, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}







