train_file: ['data/vqa_train.json',
             'data/vqa_val.json',   
             'data/vg_qa.json']
             
test_file: ['data/vqa_test.json']
## val_file: ['data/vqa_val_updated.json']
answer_list: 'data/answer_list.json'

vqa_root: '/home/crk/Desktop/ALBEF/mscoco/images/' #train2014/
vg_root: '/home/crk/Desktop/ALBEF/images/VG_100K/'  #image/

image_res: 224
batch_size_train: 4
batch_size_test: 4
k_test: 4

alpha: 0.4
distill: True
warm_up: True

eos: '[SEP]'

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 5, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}







